### ISSUE TITLE
tls/install-certs.yml playbook deletes rpc_server

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/deployment-automation#72]
[tls/install-certs.yml](https://github.com/redpanda-data/deployment-automation/blob/main/ansible/playbooks/tls/install-certs.yml#L21-L46): This part of the code sets `redpanda` again so it deletes whatever we had inside `redpanda` field in `redpanda.yaml`. we might be deleting important user configurations such as rpc_server or additional node properties.

We should instead set `kafka_api_tls` and `rpc_server_tls` separately via rpk:

instead of:

```
  - name: Configure via RPK
    shell:
      cmd: |
        rpk redpanda config set redpanda "
          kafka_api:
          - name: default
            address: {{ hostvars[inventory_hostname]['private_ip'] }}
            port: 9092
          advertised_kafka_api:
          - name: default
            address: {{ inventory_hostname }}
            port: 9092
          kafka_api_tls:
          - name: default
            enabled: true
            require_client_auth: false
            cert_file: /etc/redpanda/certs/node.crt
            key_file: /etc/redpanda/certs/node.key
            truststore_file: /etc/redpanda/certs/truststore.pem
          rpc_server_tls:
            enabled: true
            require_client_auth: false
            cert_file: /etc/redpanda/certs/node.crt
            key_file: /etc/redpanda/certs/node.key
            truststore_file: /etc/redpanda/certs/truststore.pem
        " --format yaml
```

do:
```
- name: Configure via RPK
    shell:
      cmd: |
        set -e
         
        rpk redpanda config set redpanda.kafka_api_tls "
          - name: default
            enabled: true
            require_client_auth: false
            cert_file: /etc/redpanda/certs/node.crt
            key_file: /etc/redpanda/certs/node.key
            truststore_file: /etc/redpanda/certs/truststore.pem
         " --format yaml

        rpk redpanda config set redpanda.rpc_server_tls "
            enabled: true
            require_client_auth: false
            cert_file: /etc/redpanda/certs/node.crt
            key_file: /etc/redpanda/certs/node.key
            truststore_file: /etc/redpanda/certs/truststore.pem
         " --format yaml
```

**Comment by r-vasquez** [comment]
We also should update the rpk configuration properly:

```
rpk redpanda config set 'rpk.kafka_api' "
            tls:
              truststore_file: /etc/redpanda/certs/truststore.pem
              cert_file: /etc/redpanda/certs/node.crt
              key_file: /etc/redpanda/certs/node.key
        " --format yaml
and
rpk redpanda config set 'rpk.admin_api' "
            tls:
              truststore_file: /etc/redpanda/certs/truststore.pem
              cert_file: /etc/redpanda/certs/node.crt
              key_file: /etc/redpanda/certs/node.key
        " --format yaml
```

**Comment by r-vasquez** [comment]
Final "Configure via RPK" should look like:

```yaml
  - name: Configure via RPK
    shell:
      cmd: |
        set -e

        rpk redpanda config set redpanda.kafka_api "
          - name: default
            address: {{ hostvars[inventory_hostname]['private_ip'] }}
            port: 9092
        " --format yaml

        rpk redpanda config set redpanda.advertised_kafka_api "
          - name: default
            address: {{ inventory_hostname }}
            port: 9092
        " --format yaml
        
        rpk redpanda config set redpanda.kafka_api_tls "
          - name: default
            enabled: true
            require_client_auth: false
            cert_file: /etc/redpanda/certs/node.crt
            key_file: /etc/redpanda/certs/node.key
            truststore_file: /etc/redpanda/certs/truststore.pem
        " --format yaml

        rpk redpanda config set redpanda.rpc_server_tls "
            enabled: true
            require_client_auth: false
            cert_file: /etc/redpanda/certs/node.crt
            key_file: /etc/redpanda/certs/node.key
            truststore_file: /etc/redpanda/certs/truststore.pem
        " --format yaml

        rpk redpanda config set 'rpk.kafka_api' "
            tls:
              truststore_file: /etc/redpanda/certs/truststore.pem
              cert_file: /etc/redpanda/certs/node.crt
              key_file: /etc/redpanda/certs/node.key
        " --format yaml
        
        chown -R redpanda:redpanda /etc/redpanda
```
